name: Morning Brief Podcast

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'   # 04:00 UTC daily
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate episode and RSS
        env:
          GH_PAGES_URL: ${{ secrets.GH_PAGES_URL }}
        run: |
          python generate_brief.py

      - name: Commit & push outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*
          git commit -m "Publish daily episode" || echo "No changes"
          git push
